export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  ADMIN_LOGIN: '/admin/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  MY_PROJECTS: '/my-projects',
  PROJECT_NEW: '/projects/new',
  PROJECT_DETAIL: (id: string) => `/projects/${id}`,
  PROJECT_EDIT: (id: string) => `/projects/${id}/edit`,
  WEEKLY_UPDATE_NEW: (projectId: string) => `/projects/${projectId}/weekly-update/new`,
  WEEKLY_UPDATE_EDIT: (projectId: string, updateId: string) => `/projects/${projectId}/weekly-update/${updateId}/edit`,
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  CHANGE_PASSWORD: '/change-password',
  SEARCH: '/search',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_DETAIL: (id: string) => `/admin/users/${id}`,
  ADMIN_PROJECTS: '/admin/projects',
  ADMIN_PROJECT_DETAIL: (id: string) => `/admin/projects/${id}`,
  ADMIN_EDIT_REQUESTS: '/admin/edit-requests',
  ADMIN_REPORTS: '/admin/reports',
} as const;
